# TCL File Generated by Component Editor 16.0
# Mon Jun 27 19:00:00 BRT 2016
# DO NOT MODIFY


# 
# rgb2grey_filter "Luminance Filter" v1.0
# Altera 2016.06.27.19:00:00
# RGB to Greyscale converter
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module rgb2grey_filter
# 
set_module_property DESCRIPTION "RGB to Greyscale converter"
set_module_property NAME rgb2grey_filter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Altera
set_module_property DISPLAY_NAME "Luminance Filter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL alt_vip_rgb2grey
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property quartus_synth ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file alt_vip_common_control_packet_decoder.v VERILOG PATH alt_vip_common_control_packet_decoder.v
add_fileset_file alt_vip_common_control_packet_encoder.v VERILOG PATH alt_vip_common_control_packet_encoder.v
add_fileset_file alt_vip_common_flow_control_wrapper.v VERILOG PATH alt_vip_common_flow_control_wrapper.v
add_fileset_file alt_vip_common_stream_input.v VERILOG PATH alt_vip_common_stream_input.v
add_fileset_file alt_vip_common_stream_output.v VERILOG PATH alt_vip_common_stream_output.v
add_fileset_file alt_vip_rgb2grey.v VERILOG PATH alt_vip_rgb2grey.v TOP_LEVEL_FILE
add_fileset_file alt_vip_rgb2grey_core.v VERILOG PATH alt_vip_rgb2grey_core.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL alt_vip_rgb2grey
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_verilog ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file alt_vip_common_control_packet_decoder.v VERILOG PATH alt_vip_common_control_packet_decoder.v
add_fileset_file alt_vip_common_control_packet_encoder.v VERILOG PATH alt_vip_common_control_packet_encoder.v
add_fileset_file alt_vip_common_flow_control_wrapper.v VERILOG PATH alt_vip_common_flow_control_wrapper.v
add_fileset_file alt_vip_common_stream_input.v VERILOG PATH alt_vip_common_stream_input.v
add_fileset_file alt_vip_common_stream_output.v VERILOG PATH alt_vip_common_stream_output.v
add_fileset_file alt_vip_rgb2grey.v VERILOG PATH alt_vip_rgb2grey.v
add_fileset_file alt_vip_rgb2grey_core.v VERILOG PATH alt_vip_rgb2grey_core.v


# 
# parameters
# 
add_parameter BITS_PER_SYMBOL INTEGER 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL TYPE INTEGER
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter SYMBOLS_PER_BEAT INTEGER 3
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 3
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT TYPE INTEGER
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point din
# 
add_interface din avalon_streaming end
set_interface_property din associatedClock clock
set_interface_property din associatedReset reset
set_interface_property din dataBitsPerSymbol 8
set_interface_property din errorDescriptor ""
set_interface_property din firstSymbolInHighOrderBits true
set_interface_property din maxChannel 0
set_interface_property din readyLatency 1
set_interface_property din ENABLED true
set_interface_property din EXPORT_OF ""
set_interface_property din PORT_NAME_MAP ""
set_interface_property din CMSIS_SVD_VARIABLES ""
set_interface_property din SVD_ADDRESS_GROUP ""

add_interface_port din din_ready ready Output 1
add_interface_port din din_valid valid Input 1
add_interface_port din din_sop startofpacket Input 1
add_interface_port din din_eop endofpacket Input 1
add_interface_port din din_data data Input BITS_PER_SYMBOL*SYMBOLS_PER_BEAT


# 
# connection point dout
# 
add_interface dout avalon_streaming start
set_interface_property dout associatedClock clock
set_interface_property dout associatedReset reset
set_interface_property dout dataBitsPerSymbol 8
set_interface_property dout errorDescriptor ""
set_interface_property dout firstSymbolInHighOrderBits true
set_interface_property dout maxChannel 0
set_interface_property dout readyLatency 1
set_interface_property dout ENABLED true
set_interface_property dout EXPORT_OF ""
set_interface_property dout PORT_NAME_MAP ""
set_interface_property dout CMSIS_SVD_VARIABLES ""
set_interface_property dout SVD_ADDRESS_GROUP ""

add_interface_port dout dout_ready ready Input 1
add_interface_port dout dout_valid valid Output 1
add_interface_port dout dout_data data Output BITS_PER_SYMBOL*SYMBOLS_PER_BEAT
add_interface_port dout dout_sop startofpacket Output 1
add_interface_port dout dout_eop endofpacket Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

