# TCL File Generated by Component Editor 16.0
# Sun Jun 26 22:50:15 BRT 2016
# DO NOT MODIFY


# 
# ABS_Filter "Absolute Difference Filter" v1.0
# Rodrigo Travessini 2016.06.26.22:50:15
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module ABS_Filter
# 
set_module_property DESCRIPTION ""
set_module_property NAME ABS_Filter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Rodrigo Travessini"
set_module_property DISPLAY_NAME "Absolute Difference Filter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL abs_filter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file abs_filter.v VERILOG PATH abs_filter.v TOP_LEVEL_FILE
add_fileset_file abs_filter_core.v VERILOG PATH abs_filter_core.v
add_fileset_file alt_vip_common_control_packet_decoder.v VERILOG PATH alt_vip_common_control_packet_decoder.v
add_fileset_file alt_vip_common_control_packet_encoder.v VERILOG PATH alt_vip_common_control_packet_encoder.v
add_fileset_file alt_vip_common_stream_input.v VERILOG PATH alt_vip_common_stream_input.v
add_fileset_file alt_vip_common_stream_output.v VERILOG PATH alt_vip_common_stream_output.v
add_fileset_file vip_two_inputs_flow_control_wrapper.v VERILOG PATH vip_two_inputs_flow_control_wrapper.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL abs_filter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file abs_filter.v VERILOG PATH abs_filter.v
add_fileset_file abs_filter_core.v VERILOG PATH abs_filter_core.v
add_fileset_file alt_vip_common_control_packet_decoder.v VERILOG PATH alt_vip_common_control_packet_decoder.v
add_fileset_file alt_vip_common_control_packet_encoder.v VERILOG PATH alt_vip_common_control_packet_encoder.v
add_fileset_file alt_vip_common_stream_input.v VERILOG PATH alt_vip_common_stream_input.v
add_fileset_file alt_vip_common_stream_output.v VERILOG PATH alt_vip_common_stream_output.v
add_fileset_file vip_two_inputs_flow_control_wrapper.v VERILOG PATH vip_two_inputs_flow_control_wrapper.v


# 
# parameters
# 
add_parameter BITS_PER_SYMBOL INTEGER 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL TYPE INTEGER
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter SYMBOLS_PER_BEAT INTEGER 3
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 3
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT TYPE INTEGER
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point dina
# 
add_interface dina avalon_streaming end
set_interface_property dina associatedClock clock
set_interface_property dina associatedReset reset
set_interface_property dina dataBitsPerSymbol 8
set_interface_property dina errorDescriptor ""
set_interface_property dina firstSymbolInHighOrderBits true
set_interface_property dina maxChannel 0
set_interface_property dina readyLatency 1
set_interface_property dina ENABLED true
set_interface_property dina EXPORT_OF ""
set_interface_property dina PORT_NAME_MAP ""
set_interface_property dina CMSIS_SVD_VARIABLES ""
set_interface_property dina SVD_ADDRESS_GROUP ""

add_interface_port dina asi_dinA_ready ready Output 1
add_interface_port dina asi_dinA_valid valid Input 1
add_interface_port dina asi_dinA_startofpacket startofpacket Input 1
add_interface_port dina asi_dinA_endofpacket endofpacket Input 1
add_interface_port dina asi_dinA_data data Input BITS_PER_SYMBOL*SYMBOLS_PER_BEAT


# 
# connection point dinb
# 
add_interface dinb avalon_streaming end
set_interface_property dinb associatedClock clock
set_interface_property dinb associatedReset reset
set_interface_property dinb dataBitsPerSymbol 8
set_interface_property dinb errorDescriptor ""
set_interface_property dinb firstSymbolInHighOrderBits true
set_interface_property dinb maxChannel 0
set_interface_property dinb readyLatency 1
set_interface_property dinb ENABLED true
set_interface_property dinb EXPORT_OF ""
set_interface_property dinb PORT_NAME_MAP ""
set_interface_property dinb CMSIS_SVD_VARIABLES ""
set_interface_property dinb SVD_ADDRESS_GROUP ""

add_interface_port dinb asi_dinB_ready ready Output 1
add_interface_port dinb asi_dinB_valid valid Input 1
add_interface_port dinb asi_dinB_startofpacket startofpacket Input 1
add_interface_port dinb asi_dinB_endofpacket endofpacket Input 1
add_interface_port dinb asi_dinB_data data Input BITS_PER_SYMBOL*SYMBOLS_PER_BEAT


# 
# connection point dout
# 
add_interface dout avalon_streaming start
set_interface_property dout associatedClock clock
set_interface_property dout associatedReset reset
set_interface_property dout dataBitsPerSymbol 8
set_interface_property dout errorDescriptor ""
set_interface_property dout firstSymbolInHighOrderBits true
set_interface_property dout maxChannel 0
set_interface_property dout readyLatency 1
set_interface_property dout ENABLED true
set_interface_property dout EXPORT_OF ""
set_interface_property dout PORT_NAME_MAP ""
set_interface_property dout CMSIS_SVD_VARIABLES ""
set_interface_property dout SVD_ADDRESS_GROUP ""

add_interface_port dout aso_dout_ready ready Input 1
add_interface_port dout aso_dout_valid valid Output 1
add_interface_port dout aso_dout_startofpacket startofpacket Output 1
add_interface_port dout aso_dout_endofpacket endofpacket Output 1
add_interface_port dout aso_dout_data data Output BITS_PER_SYMBOL*SYMBOLS_PER_BEAT

